#!/bin/bash

mkdir /home/pi/inter_up_test

echo "Versioning UP!"
sudo chmod +x /home/pi/scoreboard-git/scoreboard/scoreboard/ViewHierarchy/FlaskRPC.py
sudo chmod +x /home/pi/scoreboard-git/scoreboard/scoreboard/update/update.py

sync
